# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Get request with environment variables
GET http://localhost:8080/students
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/students
Content-Type: application/json

{
  "id": 10010,
  "name": "John",
  "passportNumber": "AH123456"
}

###